# KXM BLUEFIRE v23
# Windows PowerShell 5.1 / WinForms. ASCII-only source.
Set-StrictMode -Version 2.0
$ErrorActionPreference='SilentlyContinue'
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$Root=Join-Path $env:ProgramData 'KXM\BlueFire'
$BackupRoot=Join-Path $Root 'Backups'
$SessionRoot=Join-Path $Root 'Sessions'
$LogRoot=Join-Path $Root 'Logs'
$Pointer=Join-Path $Root 'CURRENT_BASELINE.txt'
$SessionFile=Join-Path $SessionRoot 'ACTIVE_SESSION.xml'
$LogFile=Join-Path $LogRoot 'KXM.log'
$LangFile=Join-Path $PSScriptRoot 'KXM_LANG_V23.json'
New-Item -ItemType Directory -Path $BackupRoot -Force|Out-Null
New-Item -ItemType Directory -Path $SessionRoot -Force|Out-Null
New-Item -ItemType Directory -Path $LogRoot -Force|Out-Null
$TX=Get-Content -LiteralPath $LangFile -Raw -Encoding UTF8|ConvertFrom-Json
$Script:Lang='en'

function L($key){$set=$TX.PSObject.Properties[$Script:Lang].Value;$p=$set.PSObject.Properties[$key];if($p){return [string]$p.Value};return $key}
function Log($s){try{Add-Content $LogFile -Value ('[{0}] {1}'-f(Get-Date -Format 'yyyy-MM-dd HH:mm:ss'),$s)-Encoding UTF8}catch{}}
function RegD($p,$n,$v){try{New-Item $p -Force|Out-Null;New-ItemProperty $p -Name $n -PropertyType DWord -Value $v -Force|Out-Null}catch{}}
function RegS($p,$n,$v){try{New-Item $p -Force|Out-Null;New-ItemProperty $p -Name $n -PropertyType String -Value $v -Force|Out-Null}catch{}}
function Snap($p,$n){$e=$false;$v=$null;$k='DWord';try{$i=Get-ItemProperty -LiteralPath $p -ErrorAction Stop;$x=$i.PSObject.Properties[$n];if($x){$e=$true;$v=$x.Value;if($v -is [string]){$k='String'}}}catch{};return [pscustomobject]@{Path=$p;Name=$n;Exists=$e;Value=$v;Kind=$k}}
function RestoreSnap($e){if($e.Exists){if($e.Kind -eq 'String'){RegS $e.Path $e.Name ([string]$e.Value)}else{RegD $e.Path $e.Name ([int64]$e.Value)}}else{Remove-ItemProperty -LiteralPath $e.Path -Name $e.Name -ErrorAction SilentlyContinue}}
function DiskInfo{$h=$false;$s=$false;try{foreach($d in @(Get-PhysicalDisk)){$m=[string]$d.MediaType;if($m -match 'HDD'){$h=$true};if($m -match 'SSD'){$s=$true}}}catch{};if(-not $h -and -not $s){try{foreach($d in @(Get-CimInstance Win32_DiskDrive)){$m=([string]$d.Model+' '+[string]$d.MediaType+' '+[string]$d.InterfaceType);if($m -match 'SSD|Solid State|NVMe'){$s=$true}elseif($m -match 'HDD|Hard Disk'){$h=$true}}}catch{}};return [pscustomobject]@{HDD=$h;SSD=$s}}
function Hardware{$c=Get-CimInstance Win32_Processor|Select-Object -First 1;$cs=Get-CimInstance Win32_ComputerSystem;$g=@(Get-CimInstance Win32_VideoController);$d=DiskInfo;$ram=0;if($cs){$ram=[math]::Round($cs.TotalPhysicalMemory/1GB,1)};$gpu='Unknown';foreach($x in $g){if($gpu -eq 'Unknown'){$gpu=[string]$x.Name}else{$gpu+=' | '+[string]$x.Name}};return [pscustomobject]@{CPU=if($c){[string]$c.Name}else{'Unknown'};Cores=if($c){[int]$c.NumberOfCores}else{0};Threads=if($c){[int]$c.NumberOfLogicalProcessors}else{0};RAM=$ram;GPU=$gpu;HDD=$d.HDD;SSD=$d.SSD;Virtualization=if($c){[bool]$c.VirtualizationFirmwareEnabled}else{$false}}}
function Recommendation($h){$c=4;$r=4;if($h.Threads -lt 4){$c=2};if($h.RAM -lt 8){$r=2};return [pscustomobject]@{Cores=$c;RAM=$r;Mode='High Performance';FPS='120 recommended / 240 ceiling optional';SysMain=if($h.HDD -or $h.RAM -le 8){'KEEP AUTO'}else{'OPTIONAL'}}}
function BlueStacksPath{foreach($p in @("$env:ProgramFiles\BlueStacks_nxt\HD-Player.exe","$env:ProgramFiles\BlueStacks_nxt5\HD-Player.exe","${env:ProgramFiles(x86)}\BlueStacks_nxt\HD-Player.exe","${env:ProgramFiles(x86)}\BlueStacks_nxt5\HD-Player.exe")){if($p -and(Test-Path $p)){return $p}};return $null}
function PendingReboot{$a=Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending';$b=Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired';return($a -or $b)}
function Conflicts{$list=New-Object System.Collections.ArrayList;$p=Get-Process -Name Discord -ErrorAction SilentlyContinue;if($p){$list.Add('Discord running')};$p=Get-Process -Name RivaTunerStatisticsServer -ErrorAction SilentlyContinue;if($p){$list.Add('RTSS running')};$s=Get-Service vmms -ErrorAction SilentlyContinue;if($s -and $s.Status -eq 'Running'){$list.Add('Hyper-V service running')};$s=Get-Service com.docker.service -ErrorAction SilentlyContinue;if($s -and $s.Status -eq 'Running'){$list.Add('Docker service running')};return $list}
function CreateBaseline{if(Test-Path $Pointer){$d=(Get-Content $Pointer -Raw -Encoding UTF8).Trim();if($d -and(Test-Path(Join-Path $d 'Baseline.xml'))){return $d}};$d=Join-Path $BackupRoot(Get-Date -Format 'yyyyMMdd_HHmmss');New-Item -ItemType Directory $d -Force|Out-Null;$st=[ordered]@{Created=(Get-Date).ToString('o');Power=((powercfg /getactivescheme)-join ' ');Registry=New-Object System.Collections.ArrayList;Services=New-Object System.Collections.ArrayList};foreach($x in @(@('HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile','SystemResponsiveness'),@('HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile','NetworkThrottlingIndex'),@('HKLM:\SYSTEM\CurrentControlSet\Control\PriorityControl','Win32PrioritySeparation'),@('HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling','PowerThrottlingOff'),@('HKLM:\SYSTEM\CurrentControlSet\Control\GraphicsDrivers','HwSchMode'),@('HKLM:\SOFTWARE\Microsoft\Windows\Dwm','OverlayTestMode'),@('HKCU:\Software\Microsoft\GameBar','AutoGameModeEnabled'),@('HKCU:\System\GameConfigStore','GameDVR_Enabled'))){$st.Registry.Add((Snap $x[0] $x[1]))};try{$s=Get-CimInstance Win32_Service -Filter "Name='SysMain'";$st.Services.Add([pscustomobject]@{Name='SysMain';Start=[string]$s.StartMode;State=[string]$s.State})}catch{};$st|Export-Clixml(Join-Path $d 'Baseline.xml');powercfg /list|Out-File(Join-Path $d 'PowerPlans.txt')-Encoding UTF8;bcdedit /enum all|Out-File(Join-Path $d 'BCD.txt')-Encoding UTF8;Set-Content $Pointer $d -Encoding UTF8;Log('Baseline created: '+$d);return $d}
function EnsureBaseline{$null=CreateBaseline}
function RestoreBaseline{$d=$null;if(Test-Path $Pointer){$d=(Get-Content $Pointer -Raw -Encoding UTF8).Trim()};if(-not $d){[System.Windows.Forms.MessageBox]::Show('No KXM baseline found.','KXM // Restore')|Out-Null;return};$f=Join-Path $d 'Baseline.xml';if(-not(Test-Path $f)){return};$a=[System.Windows.Forms.MessageBox]::Show('Restore the settings captured BEFORE KXM?','KXM // Restore',[System.Windows.Forms.MessageBoxButtons]::YesNo,[System.Windows.Forms.MessageBoxIcon]::Warning);if($a -ne [System.Windows.Forms.DialogResult]::Yes){return};$st=Import-Clixml $f;foreach($e in $st.Registry){RestoreSnap $e};foreach($s in $st.Services){if($s.Start -eq 'Auto'){Set-Service $s.Name -StartupType Automatic}elseif($s.Start -eq 'Manual'){Set-Service $s.Name -StartupType Manual}elseif($s.Start -eq 'Disabled'){Set-Service $s.Name -StartupType Disabled};if($s.State -eq 'Running'){Start-Service $s.Name}else{if($s.State -eq 'Stopped'){Stop-Service $s.Name -Force}}};if($st.Power -match '([0-9a-fA-F-]{36})'){powercfg /setactive $Matches[1]|Out-Null};Log('Restore completed');[System.Windows.Forms.MessageBox]::Show('Restore completed. Reboot Windows.','KXM')|Out-Null}
function StartSession{$d=EnsureBaseline;if(Test-Path $SessionFile){return 'Session already active.'};$p=Get-Process -Name HD-Player -ErrorAction SilentlyContinue|Select-Object -First 1;$st=[ordered]@{Started=(Get-Date).ToString('o');Power=((powercfg /getactivescheme)-join ' ');Priority=if($p){[string]$p.PriorityClass}else{'Idle'}};$st|Export-Clixml $SessionFile;foreach($x in @($env:TEMP,(Join-Path $env:LOCALAPPDATA 'Temp'),'C:\Windows\Temp')){if(Test-Path $x){Remove-Item -LiteralPath(Join-Path $x '*')-Recurse -Force -ErrorAction SilentlyContinue}};ipconfig /flushdns|Out-Null;powercfg /setactive SCHEME_MIN|Out-Null;if($p){try{$p.PriorityClass='AboveNormal'}catch{}};Log('Session start');return 'GAME READY ACTIVE.`r`nTemp cleanup complete.`r`nDNS flushed.`r`nHigh Performance active.'}
function EndSession{if(-not(Test-Path $SessionFile)){return 'No active KXM gaming session.'};$s=Import-Clixml $SessionFile;if($s.Power-match'([0-9a-fA-F-]{36})'){powercfg /setactive $Matches[1]|Out-Null};Remove-Item $SessionFile -Force -ErrorAction SilentlyContinue;Log('Session end');return 'SESSION ENDED.`r`nOriginal power plan restored.'}
function SmartOptimize{EnsureBaseline;$h=Hardware;powercfg /setactive SCHEME_MIN|Out-Null;RegD 'HKCU:\Software\Microsoft\GameBar' 'AutoGameModeEnabled' 1;RegD 'HKCU:\System\GameConfigStore' 'GameDVR_Enabled' 0;RegD 'HKCU:\Software\Microsoft\Windows\CurrentVersion\GameDVR' 'AppCaptureEnabled' 0;$mm='HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile';$g="$mm\Tasks\Games";RegD $mm 'SystemResponsiveness' 0;RegD $mm 'NetworkThrottlingIndex' 4294967295;RegD $g 'GPU Priority' 8;RegD $g 'Priority' 6;RegD 'HKLM:\SYSTEM\CurrentControlSet\Control\PriorityControl' 'Win32PrioritySeparation' 38;RegD 'HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling' 'PowerThrottlingOff' 1;$bs=BlueStacksPath;if($bs){RegS 'HKCU:\Software\Microsoft\DirectX\UserGpuPreferences' $bs 'GpuPreference=2;'};if($h.HDD -or $h.RAM -le 8){Set-Service SysMain -StartupType Automatic;Start-Service SysMain};Log('Smart optimize');return(Get-Recommendation $h)}

$form=New-Object System.Windows.Forms.Form;$form.Text='KXM // BLUEFIRE v23';$form.Size=New-Object System.Drawing.Size(1240,820);$form.StartPosition='CenterScreen';$form.BackColor=[System.Drawing.Color]::FromArgb(8,11,16);$form.ForeColor=[System.Drawing.Color]::White;$form.Font=New-Object System.Drawing.Font('Segoe UI',10);$form.FormBorderStyle='FixedSingle';$form.MaximizeBox=$false
$header=New-Object System.Windows.Forms.Label;$header.Text='KXM // BLUEFIRE';$header.Location=New-Object System.Drawing.Point(38,22);$header.Size=New-Object System.Drawing.Size(650,50);$header.Font=New-Object System.Drawing.Font('Segoe UI Semibold',25);$header.ForeColor=[System.Drawing.Color]::FromArgb(0,230,200);$form.Controls.Add($header)
$sub=New-Object System.Windows.Forms.Label;$sub.Text=$TX.en.subtitle;$sub.Location=New-Object System.Drawing.Point(42,70);$sub.Size=New-Object System.Drawing.Size(850,30);$sub.ForeColor=[System.Drawing.Color]::Silver;$form.Controls.Add($sub)
$status=New-Object System.Windows.Forms.Label;$status.Text='● SYSTEM READY';$status.Location=New-Object System.Drawing.Point(890,28);$status.Size=New-Object System.Drawing.Size(285,42);$status.TextAlign='MiddleRight';$status.Font=New-Object System.Drawing.Font('Segoe UI Semibold',12);$status.ForeColor=[System.Drawing.Color]::FromArgb(120,255,175);$form.Controls.Add($status)

$h=Hardware;$r=Recommendation $h;$dash=New-Object System.Windows.Forms.Panel;$dash.Location=New-Object System.Drawing.Point(32,112);$dash.Size=New-Object System.Drawing.Size(1140,112);$dash.BackColor=[System.Drawing.Color]::FromArgb(18,23,31);$form.Controls.Add($dash)
$cards=@(@('CPU',$h.CPU),@('RAM',("$($h.RAM) GB")),@('GPU',$h.GPU),@('STORAGE',("HDD=$($h.HDD)  SSD=$($h.SSD)")),@('PROFILE',('FREE FIRE')));$x=14;foreach($c in $cards){$p=New-Object System.Windows.Forms.Panel;$p.Location=New-Object System.Drawing.Point($x,14);$p.Size=New-Object System.Drawing.Size(208,84);$p.BackColor=[System.Drawing.Color]::FromArgb(25,31,41);$l=New-Object System.Windows.Forms.Label;$l.Text="$($c[0])`r`n$($c[1])";$l.Dock='Fill';$l.TextAlign='MiddleCenter';$l.ForeColor=[System.Drawing.Color]::White;$p.Controls.Add($l);$dash.Controls.Add($p);$x+=222}

$quick=New-Object System.Windows.Forms.GroupBox;$quick.Text=$TX.en.quick;$quick.Location=New-Object System.Drawing.Point(32,242);$quick.Size=New-Object System.Drawing.Size(1140,120);$quick.ForeColor=[System.Drawing.Color]::FromArgb(0,230,200);$form.Controls.Add($quick)
$ready=New-Object System.Windows.Forms.Button;$ready.Text=$TX.en.ready;$ready.Location=New-Object System.Drawing.Point(18,30);$ready.Size=New-Object System.Drawing.Size(250,68);$ready.Font=New-Object System.Drawing.Font('Segoe UI Semibold',14);$ready.BackColor=[System.Drawing.Color]::FromArgb(0,126,112);$ready.ForeColor=[System.Drawing.Color]::White;$ready.FlatStyle='Flat';$quick.Controls.Add($ready)
$end=New-Object System.Windows.Forms.Button;$end.Text=$TX.en.end;$end.Location=New-Object System.Drawing.Point(285,30);$end.Size=New-Object System.Drawing.Size(220,68);$end.Font=New-Object System.Drawing.Font('Segoe UI Semibold',12);$end.BackColor=[System.Drawing.Color]::FromArgb(58,47,44);$end.ForeColor=[System.Drawing.Color]::White;$end.FlatStyle='Flat';$quick.Controls.Add($end)
$smart=New-Object System.Windows.Forms.Button;$smart.Text=$TX.en.smart;$smart.Location=New-Object System.Drawing.Point(520,30);$smart.Size=New-Object System.Drawing.Size(250,68);$smart.Font=New-Object System.Drawing.Font('Segoe UI Semibold',13);$smart.BackColor=[System.Drawing.Color]::FromArgb(34,44,58);$smart.ForeColor=[System.Drawing.Color]::White;$smart.FlatStyle='Flat';$quick.Controls.Add($smart)
$restore=New-Object System.Windows.Forms.Button;$restore.Text=$TX.en.restore;$restore.Location=New-Object System.Drawing.Point(785,30);$restore.Size=New-Object System.Drawing.Size(180,68);$restore.Font=New-Object System.Drawing.Font('Segoe UI Semibold',11);$restore.BackColor=[System.Drawing.Color]::FromArgb(68,47,44);$restore.ForeColor=[System.Drawing.Color]::White;$restore.FlatStyle='Flat';$quick.Controls.Add($restore)
$lang=New-Object System.Windows.Forms.ComboBox;$lang.DropDownStyle='DropDownList';$lang.Items.AddRange(@('English','العربية','Français'));$lang.SelectedIndex=0;$lang.Location=New-Object System.Drawing.Point(980,47);$lang.Size=New-Object System.Drawing.Size(125,34);$quick.Controls.Add($lang)

$monitor=New-Object System.Windows.Forms.GroupBox;$monitor.Text=$TX.en.live;$monitor.Location=New-Object System.Drawing.Point(32,390);$monitor.Size=New-Object System.Drawing.Size(350,300);$monitor.ForeColor=[System.Drawing.Color]::FromArgb(0,230,200);$form.Controls.Add($monitor)
$live=New-Object System.Windows.Forms.Label;$live.Location=New-Object System.Drawing.Point(20,38);$live.Size=New-Object System.Drawing.Size(310,230);$live.Font=New-Object System.Drawing.Font('Consolas',12);$live.ForeColor=[System.Drawing.Color]::FromArgb(195,245,236);$monitor.Controls.Add($live)

$tools=New-Object System.Windows.Forms.GroupBox;$tools.Text=$TX.en.tools;$tools.Location=New-Object System.Drawing.Point(402,390);$tools.Size=New-Object System.Drawing.Size(770,300);$tools.ForeColor=[System.Drawing.Color]::FromArgb(0,230,200);$form.Controls.Add($tools)
$details=New-Object System.Windows.Forms.TextBox;$details.Multiline=$true;$details.ReadOnly=$true;$details.ScrollBars='Vertical';$details.Location=New-Object System.Drawing.Point(32,705);$details.Size=New-Object System.Drawing.Size(1140,70);$details.BackColor=[System.Drawing.Color]::FromArgb(13,17,23);$details.ForeColor=[System.Drawing.Color]::FromArgb(195,245,236);$details.BorderStyle='FixedSingle';$details.Font=New-Object System.Drawing.Font('Consolas',10);$form.Controls.Add($details)

$names=@('Hardware Audit','Game Profiles','Conflict Check','Before/After','Backup Center','Verify','Network','System Health','Reboot Status','Experimental');$i=0
foreach($name in $names){$b=New-Object System.Windows.Forms.Button;$b.Text=$name;$b.Tag=$name;$col=$i%5;$row=[math]::Floor($i/5);$b.Location=New-Object System.Drawing.Point((18+150*$col),(35+92*$row));$b.Size=New-Object System.Drawing.Size(138,65);$b.BackColor=[System.Drawing.Color]::FromArgb(27,34,44);$b.ForeColor=[System.Drawing.Color]::White;$b.FlatStyle='Flat';$b.Add_Click({$n=$this.Tag;$hh=Hardware;$rr=Recommendation $hh;if($n -eq 'Hardware Audit'){$details.Text=("CPU: {0}`r`nCores/Threads: {1}/{2}`r`nRAM: {3} GB`r`nGPU: {4}`r`nHDD: {5}  SSD: {6}`r`nVirtualization: {7}`r`nRecommendation: 4 cores / 4 GB / High Performance"-f$hh.CPU,$hh.Cores,$hh.Threads,$hh.RAM,$hh.GPU,$hh.HDD,$hh.SSD,$hh.Virtualization)}elseif($n -eq 'Game Profiles'){$details.Text='FREE FIRE / FREE FIRE MAX`r`n`r`nBlueStacks: 4 CPU cores`r`nBlueStacks: 4 GB RAM`r`nMode: High Performance`r`nFPS target: 120 recommended`r`n240 FPS: optional ceiling, not guaranteed'}elseif($n -eq 'Conflict Check'){$c=Conflicts;if($c.Count -eq 0){$details.Text='CONFLICT CHECK`r`n`r`nNo common conflicts detected.'}else{$details.Text='CONFLICT CHECK`r`n`r`n'+($c -join "`r`n")}}elseif($n -eq 'Before/After'){$file=Join-Path $Root 'LastBenchmark.xml';$snap=[ordered]@{Time=(Get-Date).ToString('o');CPU=$hh.CPU;RAM=$hh.RAM;GPU=$hh.GPU;CPULoad=(try{(Get-CimInstance Win32_Processor|Measure-Object LoadPercentage -Average).Average}catch{0});MemoryUsed=(MemUsed);Power=((powercfg /getactivescheme)-join ' ')};$old=$null;if(Test-Path $file){$old=Import-Clixml $file};$snap|Export-Clixml $file;if($old){$details.Text=("BEFORE / AFTER`r`n`r`nPrevious CPU Load: {0}`r`nCurrent CPU Load: {1}`r`nPrevious RAM Used: {2} GB`r`nCurrent RAM Used: {3} GB`r`n`r`nThis is a system snapshot; enter real in-game FPS separately."-f$old.CPULoad,$snap.CPULoad,$old.MemoryUsed,$snap.MemoryUsed)}else{$details.Text='BASELINE SNAPSHOT SAVED.`r`nRun this action again after testing to compare.'}}elseif($n -eq 'Backup Center'){$details.Text=('BASELINE: '+((CreateBaseline)))}elseif($n -eq 'Verify'){$details.Text=("Power: {0}`r`nSysMain: {1}`r`nHAGS: {2}`r`nPending reboot: {3}"-f((powercfg /getactivescheme)-join ' '),(Get-Service SysMain).StartType,(Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\GraphicsDrivers' -ErrorAction SilentlyContinue).HwSchMode,(PendingReboot))}elseif($n -eq 'Network'){NetOptimize;$details.Text='NETWORK PROFILE APPLIED.`r`nRSS enabled.`r`nTCP autotuning normal.'}elseif($n -eq 'System Health'){$free=(Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='C:'");$details.Text=("SYSTEM HEALTH`r`n`r`nC: Free: {0:N1} GB`r`nPower: {1}`r`nReboot pending: {2}`r`nConflicts: {3}"-f($free.FreeSpace/1GB),((powercfg /getactivescheme)-join ' '),(PendingReboot),(Conflicts).Count)}elseif($n -eq 'Reboot Status'){$details.Text=('REBOOT REQUIRED: '+(PendingReboot))}else{$details.Text='Experimental settings remain opt-in.`r`nNo kernel/BCD change is performed from this button.'}});$tools.Controls.Add($b);$i++}

$ready.Add_Click({$details.Text=StartSession;$status.Text='● GAME SESSION ACTIVE'})
$end.Add_Click({$details.Text=EndSession;$status.Text='● SYSTEM READY'})
$smart.Add_Click({$ans=[System.Windows.Forms.MessageBox]::Show('Apply the hardware-aware KXM profile?','KXM // Smart Optimize',[System.Windows.Forms.MessageBoxButtons]::YesNo,[System.Windows.Forms.MessageBoxIcon]::Question);if($ans -eq [System.Windows.Forms.DialogResult]::Yes){$rr=SmartOptimize;$details.Text=("SMART OPTIMIZE COMPLETE`r`n`r`nBlueStacks: {0} CPU cores / {1} GB RAM`r`nMode: {2}`r`nFPS: {3}`r`nSysMain: {4}"-f$rr.Cores,$rr.RAM,$rr.Mode,$rr.FPS,$rr.SysMain);$status.Text='● OPTIMIZED'}})
$restore.Add_Click({RestoreBaseline;$status.Text='● RESTORED'})
$lang.Add_SelectedIndexChanged({if($lang.SelectedItem -eq 'العربية'){$Script:Lang='ar';$form.RightToLeft='Yes';$form.RightToLeftLayout=$true;$sub.Text=$TX.ar.subtitle;$status.Text=$TX.ar.system_ready}elseif($lang.SelectedItem -eq 'Français'){$Script:Lang='fr';$form.RightToLeft='No';$form.RightToLeftLayout=$false;$sub.Text=$TX.fr.subtitle;$status.Text=$TX.fr.system_ready}else{$Script:Lang='en';$form.RightToLeft='No';$form.RightToLeftLayout=$false;$sub.Text=$TX.en.subtitle;$status.Text=$TX.en.system_ready}})

$timer=New-Object System.Windows.Forms.Timer;$timer.Interval=2000;$timer.Add_Tick({$bs='OFF';if(Get-Process -Name HD-Player -ErrorAction SilentlyContinue){$bs='ACTIVE'};$live.Text=("CPU LOAD   {0,3}%`r`nRAM USED   {1,4} GB / {2,4} GB`r`nBLUESTACKS {3}`r`n`r`nHDD        {4}`r`nSSD        {5}`r`nVIRTUAL    {6}`r`n`r`nPROFILE    FREE FIRE`r`nBS RAM     4 GB`r`nBS CPU     4 CORES`r`nFPS       120 rec / 240 cap"-f(CpuLoad),(MemUsed),$h.RAM,$bs,$h.HDD,$h.SSD,$h.Virtualization)});$timer.Start()

$form.Add_FormClosing({if(Test-Path $SessionFile){EndSession|Out-Null}})
$form.Add_Shown({$form.Activate()})
[void]$form.ShowDialog()
