# KXM BLUEFIRE v22
# Windows PowerShell 5.1 + WinForms.
# ASCII-only source. UI text is stored in KXM_LANG_V22.json.
Set-StrictMode -Version 2.0
$ErrorActionPreference='SilentlyContinue'
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$Root=Join-Path $env:ProgramData 'KXM\BlueFire'
$BackupRoot=Join-Path $Root 'Backups'
$SessionRoot=Join-Path $Root 'Sessions'
$LogRoot=Join-Path $Root 'Logs'
$BaselinePointer=Join-Path $Root 'CURRENT_BASELINE.txt'
$SessionFile=Join-Path $SessionRoot 'ACTIVE_SESSION.xml'
$LogFile=Join-Path $LogRoot 'KXM.log'
$LangPath=Join-Path $PSScriptRoot 'KXM_LANG_V22.json'
New-Item -ItemType Directory -Path $BackupRoot -Force|Out-Null
New-Item -ItemType Directory -Path $SessionRoot -Force|Out-Null
New-Item -ItemType Directory -Path $LogRoot -Force|Out-Null
$TX=Get-Content -LiteralPath $LangPath -Raw -Encoding UTF8|ConvertFrom-Json
$Script:Lang='EN'

function T($key){$n=$key+'_'+$Script:Lang;$p=$TX.PSObject.Properties[$n];if($null -ne $p){return [string]$p.Value};$p=$TX.PSObject.Properties[$key+'_EN'];if($null -ne $p){return [string]$p.Value};return $key}
function Log($s){try{Add-Content -LiteralPath $LogFile -Value ('[{0}] {1}'-f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'),$s)-Encoding UTF8}catch{}}
function RegD($p,$n,$v){try{New-Item $p -Force|Out-Null;New-ItemProperty $p -Name $n -PropertyType DWord -Value $v -Force|Out-Null}catch{}}
function RegS($p,$n,$v){try{New-Item $p -Force|Out-Null;New-ItemProperty $p -Name $n -PropertyType String -Value $v -Force|Out-Null}catch{}}
function Snap($p,$n){$e=$false;$v=$null;$k='DWord';try{$i=Get-ItemProperty -LiteralPath $p -ErrorAction Stop;$x=$i.PSObject.Properties[$n];if($null -ne $x){$e=$true;$v=$x.Value;if($v -is [string]){$k='String'}}}catch{};return [pscustomobject]@{Path=$p;Name=$n;Exists=$e;Value=$v;Kind=$k}}
function RestoreSnap($e){if($e.Exists){if($e.Kind -eq 'String'){RegS $e.Path $e.Name ([string]$e.Value)}else{RegD $e.Path $e.Name ([int64]$e.Value)}}else{Remove-ItemProperty -LiteralPath $e.Path -Name $e.Name -ErrorAction SilentlyContinue}}
function DiskInfo{$h=$false;$s=$false;try{foreach($d in @(Get-PhysicalDisk -ErrorAction Stop)){$m=[string]$d.MediaType;if($m -match 'HDD'){$h=$true};if($m -match 'SSD'){$s=$true}}}catch{};if(-not $h -and -not $s){try{foreach($d in @(Get-CimInstance Win32_DiskDrive)){$m=([string]$d.Model+' '+[string]$d.MediaType+' '+[string]$d.InterfaceType);if($m -match 'SSD|Solid State|NVMe'){$s=$true}elseif($m -match 'HDD|Hard Disk|SATA|IDE'){$h=$true}}}catch{}};return [pscustomobject]@{HDD=$h;SSD=$s}}
function Hardware{$c=Get-CimInstance Win32_Processor|Select-Object -First 1;$cs=Get-CimInstance Win32_ComputerSystem;$g=@(Get-CimInstance Win32_VideoController);$d=DiskInfo;$ram=0;if($cs){$ram=[math]::Round($cs.TotalPhysicalMemory/1GB,1)};$gpu='Unknown';foreach($x in $g){if($gpu -eq 'Unknown'){$gpu=[string]$x.Name}else{$gpu+=' | '+[string]$x.Name}};$cpu='Unknown';$cores=0;$threads=0;$virt=$false;if($c){$cpu=[string]$c.Name;$cores=[int]$c.NumberOfCores;$threads=[int]$c.NumberOfLogicalProcessors;$virt=[bool]$c.VirtualizationFirmwareEnabled};return [pscustomobject]@{CPU=$cpu;Cores=$cores;Threads=$threads;RAM=$ram;GPU=$gpu;HDD=$d.HDD;SSD=$d.SSD;Virtualization=$virt}}
function Recommendation($h){$cores=4;$ram=4;if($h.Threads -lt 4){$cores=2};if($h.RAM -lt 8){$ram=2};$disk='HDD-safe';if($h.SSD){$disk='SSD-ready'};return [pscustomobject]@{Cores=$cores;RAM=$ram;Mode='High Performance';FPS='120 recommended / 240 ceiling optional';Disk=$disk}}
function BlueStacksPath{foreach($p in @("$env:ProgramFiles\BlueStacks_nxt\HD-Player.exe","$env:ProgramFiles\BlueStacks_nxt5\HD-Player.exe","${env:ProgramFiles(x86)}\BlueStacks_nxt\HD-Player.exe","${env:ProgramFiles(x86)}\BlueStacks_nxt5\HD-Player.exe")){if($p -and(Test-Path $p)){return $p}};return $null}
function CpuLoad{try{$c=Get-CimInstance Win32_Processor|Measure-Object -Property LoadPercentage -Average;return [math]::Round($c.Average,0)}catch{return 0}}
function MemUsed{try{$os=Get-CimInstance Win32_OperatingSystem;$total=[math]::Round($os.TotalVisibleMemorySize/1MB,1);$free=[math]::Round($os.FreePhysicalMemory/1MB,1);return [math]::Round($total-$free,1)}catch{return 0}}

function EnsureBaseline{if(Test-Path $BaselinePointer){$old=(Get-Content $BaselinePointer -Raw -Encoding UTF8).Trim();if($old -and(Test-Path(Join-Path $old 'Baseline.xml'))){return}};$d=Join-Path $BackupRoot(Get-Date -Format 'yyyyMMdd_HHmmss');New-Item -ItemType Directory $d -Force|Out-Null;$st=[ordered]@{Created=(Get-Date).ToString('o');Power=((powercfg /getactivescheme)-join ' ');Registry=New-Object System.Collections.ArrayList;Services=New-Object System.Collections.ArrayList};foreach($x in @(@('HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile','SystemResponsiveness'),@('HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile','NetworkThrottlingIndex'),@('HKLM:\SYSTEM\CurrentControlSet\Control\PriorityControl','Win32PrioritySeparation'),@('HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling','PowerThrottlingOff'),@('HKLM:\SYSTEM\CurrentControlSet\Control\GraphicsDrivers','HwSchMode'),@('HKLM:\SOFTWARE\Microsoft\Windows\Dwm','OverlayTestMode'),@('HKCU:\Software\Microsoft\GameBar','AutoGameModeEnabled'),@('HKCU:\System\GameConfigStore','GameDVR_Enabled'))){$st.Registry.Add((Snap $x[0] $x[1]))};try{$svc=Get-CimInstance Win32_Service -Filter "Name='SysMain'";$st.Services.Add([pscustomobject]@{Name='SysMain';Start=[string]$svc.StartMode;State=[string]$svc.State})}catch{};$st|Export-Clixml(Join-Path $d 'Baseline.xml');powercfg /list|Out-File(Join-Path $d 'PowerPlans.txt')-Encoding UTF8;bcdedit /enum all|Out-File(Join-Path $d 'BCD.txt')-Encoding UTF8;Set-Content $BaselinePointer $d -Encoding UTF8;Log('Baseline created: '+$d)}

function RestoreBaseline{$d=$null;if(Test-Path $BaselinePointer){$d=(Get-Content $BaselinePointer -Raw -Encoding UTF8).Trim()};if(-not $d -or -not(Test-Path(Join-Path $d 'Baseline.xml'))){[System.Windows.Forms.MessageBox]::Show((T 'NoBase'),'KXM // Restore')|Out-Null;return};$a=[System.Windows.Forms.MessageBox]::Show((T 'RestoreQ'),'KXM // Restore',[System.Windows.Forms.MessageBoxButtons]::YesNo,[System.Windows.Forms.MessageBoxIcon]::Warning);if($a -ne [System.Windows.Forms.DialogResult]::Yes){return};$st=Import-Clixml(Join-Path $d 'Baseline.xml');foreach($e in $st.Registry){RestoreSnap $e};foreach($s in $st.Services){if($s.Start -eq 'Auto'){Set-Service $s.Name -StartupType Automatic}elseif($s.Start -eq 'Manual'){Set-Service $s.Name -StartupType Manual}elseif($s.Start -eq 'Disabled'){Set-Service $s.Name -StartupType Disabled};if($s.State -eq 'Running'){Start-Service $s.Name}elseif($s.State -eq 'Stopped'){Stop-Service $s.Name -Force}};if($st.Power-match'([0-9a-fA-F-]{36})'){powercfg /setactive $Matches[1]|Out-Null};Log('Baseline restored');[System.Windows.Forms.MessageBox]::Show((T 'Restored'),'KXM // Restore')|Out-Null}

function GameReady{$session=[ordered]@{Started=(Get-Date).ToString('o');Power=((powercfg /getactivescheme)-join ' ');BlueStacksPriority=$null};if(Test-Path $SessionFile){return 'Session already active.'};$p=Get-Process -Name 'HD-Player' -ErrorAction SilentlyContinue|Select-Object -First 1;if($p){$session.BlueStacksPriority=[int]$p.PriorityClass};$session|Export-Clixml $SessionFile;EnsureBaseline;foreach($d in @($env:TEMP,(Join-Path $env:LOCALAPPDATA 'Temp'),'C:\Windows\Temp')){if(Test-Path $d){Remove-Item -LiteralPath(Join-Path $d '*')-Recurse -Force -ErrorAction SilentlyContinue}};ipconfig /flushdns|Out-Null;powercfg /setactive SCHEME_MIN|Out-Null;if($p){try{$p.PriorityClass='AboveNormal'}catch{}};Log('GAME READY start');return 'GAME READY ACTIVE.`r`nTemp cleanup complete.`r`nDNS flushed.`r`nHigh Performance active.'}
function EndGameSession{if(-not(Test-Path $SessionFile)){return 'No active KXM gaming session.'};$s=Import-Clixml $SessionFile;if($s.Power-match'([0-9a-fA-F-]{36})'){powercfg /setactive $Matches[1]|Out-Null};Remove-Item $SessionFile -Force -ErrorAction SilentlyContinue;Log('GAME SESSION ended');return 'Gaming session ended.`r`nOriginal power plan restored.'}

function SmartOptimize{EnsureBaseline;$h=Hardware;powercfg /setactive SCHEME_MIN|Out-Null;RegD 'HKCU:\Software\Microsoft\GameBar' 'AutoGameModeEnabled' 1;RegD 'HKCU:\System\GameConfigStore' 'GameDVR_Enabled' 0;RegD 'HKCU:\Software\Microsoft\Windows\CurrentVersion\GameDVR' 'AppCaptureEnabled' 0;$mm='HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile';$g="$mm\Tasks\Games";RegD $mm 'SystemResponsiveness' 0;RegD $mm 'NetworkThrottlingIndex' 4294967295;RegD $g 'GPU Priority' 8;RegD $g 'Priority' 6;RegD 'HKLM:\SYSTEM\CurrentControlSet\Control\PriorityControl' 'Win32PrioritySeparation' 38;RegD 'HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling' 'PowerThrottlingOff' 1;$bs=BlueStacksPath;if($bs){RegS 'HKCU:\Software\Microsoft\DirectX\UserGpuPreferences' $bs 'GpuPreference=2;'};if($h.HDD -or $h.RAM -le 8){Set-Service SysMain -StartupType Automatic;Start-Service SysMain};Log('SMART OPTIMIZE');return $h}
function NetOptimize{EnsureBaseline;netsh int tcp set global rss=enabled|Out-Null;netsh int tcp set global autotuninglevel=normal|Out-Null;Log('NETWORK optimize')}

$form=New-Object System.Windows.Forms.Form;$form.Text='KXM // BLUEFIRE v22';$form.Size=New-Object System.Drawing.Size(1240,820);$form.StartPosition='CenterScreen';$form.BackColor=[System.Drawing.Color]::FromArgb(8,11,16);$form.ForeColor=[System.Drawing.Color]::White;$form.Font=New-Object System.Drawing.Font('Segoe UI',10);$form.FormBorderStyle='FixedSingle';$form.MaximizeBox=$false
$header=New-Object System.Windows.Forms.Label;$header.Text='KXM // BLUEFIRE';$header.Location=New-Object System.Drawing.Point(38,22);$header.Size=New-Object System.Drawing.Size(650,50);$header.Font=New-Object System.Drawing.Font('Segoe UI Semibold',25);$header.ForeColor=[System.Drawing.Color]::FromArgb(0,230,200);$form.Controls.Add($header)
$sub=New-Object System.Windows.Forms.Label;$sub.Text='Gaming Performance Suite  •  GGOS / BlueStacks / Free Fire';$sub.Location=New-Object System.Drawing.Point(42,70);$sub.Size=New-Object System.Drawing.Size(850,30);$sub.ForeColor=[System.Drawing.Color]::Silver;$form.Controls.Add($sub)
$status=New-Object System.Windows.Forms.Label;$status.Location=New-Object System.Drawing.Point(890,28);$status.Size=New-Object System.Drawing.Size(285,42);$status.Text='● SYSTEM READY';$status.TextAlign='MiddleRight';$status.Font=New-Object System.Drawing.Font('Segoe UI Semibold',12);$status.ForeColor=[System.Drawing.Color]::FromArgb(120,255,175);$form.Controls.Add($status)

$h=Hardware;$r=Recommendation $h
$dash=New-Object System.Windows.Forms.Panel;$dash.Location=New-Object System.Drawing.Point(32,112);$dash.Size=New-Object System.Drawing.Size(1140,112);$dash.BackColor=[System.Drawing.Color]::FromArgb(18,23,31);$form.Controls.Add($dash)
$cards=@(@('CPU',$h.CPU),@('RAM',("$($h.RAM) GB")),@('GPU',$h.GPU),@('STORAGE',("HDD=$($h.HDD)  SSD=$($h.SSD)")),@('PROFILE',$r.Profile));$x=14
foreach($c in $cards){$cp=New-Object System.Windows.Forms.Panel;$cp.Location=New-Object System.Drawing.Point($x,14);$cp.Size=New-Object System.Drawing.Size(208,84);$cp.BackColor=[System.Drawing.Color]::FromArgb(25,31,41);$lb=New-Object System.Windows.Forms.Label;$lb.Text="$($c[0])`r`n$($c[1])";$lb.Dock='Fill';$lb.TextAlign='MiddleCenter';$lb.ForeColor=[System.Drawing.Color]::White;$cp.Controls.Add($lb);$dash.Controls.Add($cp);$x+=222}

$quick=New-Object System.Windows.Forms.GroupBox;$quick.Text='  QUICK PLAY  ';$quick.Location=New-Object System.Drawing.Point(32,242);$quick.Size=New-Object System.Drawing.Size(1140,120);$quick.ForeColor=[System.Drawing.Color]::FromArgb(0,230,200);$form.Controls.Add($quick)
$ready=New-Object System.Windows.Forms.Button;$ready.Text='GAME READY';$ready.Location=New-Object System.Drawing.Point(18,30);$ready.Size=New-Object System.Drawing.Size(250,68);$ready.Font=New-Object System.Drawing.Font('Segoe UI Semibold',14);$ready.BackColor=[System.Drawing.Color]::FromArgb(0,126,112);$ready.ForeColor=[System.Drawing.Color]::White;$ready.FlatStyle='Flat';$quick.Controls.Add($ready)
$end=New-Object System.Windows.Forms.Button;$end.Text='END SESSION';$end.Location=New-Object System.Drawing.Point(285,30);$end.Size=New-Object System.Drawing.Size(220,68);$end.Font=New-Object System.Drawing.Font('Segoe UI Semibold',12);$end.BackColor=[System.Drawing.Color]::FromArgb(58,47,44);$end.ForeColor=[System.Drawing.Color]::White;$end.FlatStyle='Flat';$quick.Controls.Add($end)
$smart=New-Object System.Windows.Forms.Button;$smart.Text='SMART OPTIMIZE';$smart.Location=New-Object System.Drawing.Point(520,30);$smart.Size=New-Object System.Drawing.Size(250,68);$smart.Font=New-Object System.Drawing.Font('Segoe UI Semibold',13);$smart.BackColor=[System.Drawing.Color]::FromArgb(34,44,58);$smart.ForeColor=[System.Drawing.Color]::White;$smart.FlatStyle='Flat';$quick.Controls.Add($smart)
$restore=New-Object System.Windows.Forms.Button;$restore.Text='RESTORE ORIGINAL';$restore.Location=New-Object System.Drawing.Point(785,30);$restore.Size=New-Object System.Drawing.Size(180,68);$restore.Font=New-Object System.Drawing.Font('Segoe UI Semibold',11);$restore.BackColor=[System.Drawing.Color]::FromArgb(68,47,44);$restore.ForeColor=[System.Drawing.Color]::White;$restore.FlatStyle='Flat';$quick.Controls.Add($restore)
$lang=New-Object System.Windows.Forms.ComboBox;$lang.DropDownStyle='DropDownList';$lang.Items.AddRange(@('English','العربية','Français'));$lang.SelectedIndex=0;$lang.Location=New-Object System.Drawing.Point(980,47);$lang.Size=New-Object System.Drawing.Size(125,34);$quick.Controls.Add($lang)

$monitor=New-Object System.Windows.Forms.GroupBox;$monitor.Text='  LIVE SYSTEM  ';$monitor.Location=New-Object System.Drawing.Point(32,385);$monitor.Size=New-Object System.Drawing.Size(350,300);$monitor.ForeColor=[System.Drawing.Color]::FromArgb(0,230,200);$form.Controls.Add($monitor)
$live=New-Object System.Windows.Forms.Label;$live.Location=New-Object System.Drawing.Point(20,38);$live.Size=New-Object System.Drawing.Size(310,230);$live.Font=New-Object System.Drawing.Font('Consolas',12);$live.ForeColor=[System.Drawing.Color]::FromArgb(195,245,236);$monitor.Controls.Add($live)

$tools=New-Object System.Windows.Forms.GroupBox;$tools.Text='  CONTROL CENTER  ';$tools.Location=New-Object System.Drawing.Point(402,385);$tools.Size=New-Object System.Drawing.Size(770,300);$tools.ForeColor=[System.Drawing.Color]::FromArgb(0,230,200);$form.Controls.Add($tools)
$details=New-Object System.Windows.Forms.TextBox;$details.Multiline=$true;$details.ReadOnly=$true;$details.ScrollBars='Vertical';$details.Location=New-Object System.Drawing.Point(610,710);$details.Size=New-Object System.Drawing.Size(562,70);$details.BackColor=[System.Drawing.Color]::FromArgb(13,17,23);$details.ForeColor=[System.Drawing.Color]::FromArgb(195,245,236);$details.BorderStyle='FixedSingle';$details.Font=New-Object System.Drawing.Font('Consolas',10);$form.Controls.Add($details)

$btnNames=@('Hardware Audit','Game Profiles','Conflict Check','Benchmark','Backup Center','Verify','Network','Recovery Log','System Health','Experimental')
$i=0
foreach($name in $btnNames){$b=New-Object System.Windows.Forms.Button;$b.Text=$name;$col=$i%5;$row=[math]::Floor($i/5);$b.Location=New-Object System.Drawing.Point((18+150*$col),(35+92*$row));$b.Size=New-Object System.Drawing.Size(138,65);$b.BackColor=[System.Drawing.Color]::FromArgb(27,34,44);$b.ForeColor=[System.Drawing.Color]::White;$b.FlatStyle='Flat';$b.Tag=$name;$b.Add_Click({$n=$this.Tag;$hh=Hardware;$rr=Recommendation $hh;if($n -eq 'Hardware Audit'){$details.Text=("HARDWARE AUDIT`r`n`r`nCPU: {0}`r`nCores/Threads: {1}/{2}`r`nRAM: {3} GB`r`nGPU: {4}`r`nHDD: {5}`r`nSSD: {6}`r`nVirtualization: {7}"-f $hh.CPU,$hh.Cores,$hh.Threads,$hh.RAM,$hh.GPU,$hh.HDD,$hh.SSD,$hh.Virtualization)}elseif($n -eq 'Game Profiles'){$details.Text='FREE FIRE PROFILE`r`n`r`nBlueStacks CPU: 4 cores`r`nBlueStacks RAM: 4 GB`r`nMode: High Performance`r`nFPS: 120 recommended / 240 ceiling optional`r`n`r`nFree Fire MAX uses the same base profile.'}elseif($n -eq 'Conflict Check'){$conf=@();if(Get-Process -Name 'Discord' -ErrorAction SilentlyContinue){$conf+='Discord running'};if(Get-Service 'vmms' -ErrorAction SilentlyContinue){if((Get-Service 'vmms').Status -eq 'Running'){$conf+='Hyper-V service running'}};if(Get-Process -Name 'RivaTunerStatisticsServer' -ErrorAction SilentlyContinue){$conf+='RTSS running'};if(Get-Service 'com.docker.service' -ErrorAction SilentlyContinue){if((Get-Service 'com.docker.service').Status -eq 'Running'){$conf+='Docker running'}};if($conf.Count -eq 0){$details.Text='CONFLICT CHECK`r`n`r`nNo common conflicts detected.'}else{$details.Text='CONFLICT CHECK`r`n`r`n'+($conf -join "`r`n")}}elseif($n -eq 'Benchmark'){$file=Join-Path $Root('benchmark_'+(Get-Date -Format 'yyyyMMdd_HHmmss')+'.txt');@('KXM BLUEFIRE v22',"$(Get-Date)","CPU: $($hh.CPU)","RAM: $($hh.RAM) GB","GPU: $($hh.GPU)","CPU Load: $(CpuLoad)%","Memory Used: $(MemUsed) GB","Power: $((powercfg /getactivescheme)-join ' ')")|Set-Content $file -Encoding UTF8;$details.Text='BENCHMARK SNAPSHOT SAVED`r`n`r`n'+$file}else{$details.Text=($n+'`r`n`r`nFeature ready. Use the Quick Play actions for changes.')}});$tools.Controls.Add($b);$i++}

$ready.Add_Click({$details.Text=GameReady;$status.Text='● GAME SESSION ACTIVE'})
$end.Add_Click({$details.Text=EndGameSession;$status.Text='● SYSTEM READY'})
$smart.Add_Click({$ans=[System.Windows.Forms.MessageBox]::Show('Apply the recommended profile for this hardware?','KXM // Smart Optimize',[System.Windows.Forms.MessageBoxButtons]::YesNo,[System.Windows.Forms.MessageBoxIcon]::Question);if($ans -eq [System.Windows.Forms.DialogResult]::Yes){$z=SmartOptimize;$details.Text=("SMART OPTIMIZE COMPLETE`r`n`r`nProfile: {0}`r`nBlueStacks: 4 cores / 4 GB`r`nMode: High Performance`r`nHAGS: benchmark-only`r`nBaseline: {1}"-f $r.Profile,(Get-Content $BaselinePointer -Raw));$status.Text='● OPTIMIZED'}})
$restore.Add_Click({RestoreBaseline;$status.Text='● RESTORE COMPLETE'})
$lang.Add_SelectedIndexChanged({if($lang.SelectedItem -eq 'العربية'){$form.RightToLeft='Yes';$form.RightToLeftLayout=$true;$sub.Text='مجموعة أداء الألعاب  •  GGOS / BlueStacks / Free Fire';$status.Text='● النظام جاهز'}elseif($lang.SelectedItem -eq 'Français'){$form.RightToLeft='No';$form.RightToLeftLayout=$false;$sub.Text='Suite de performance gaming  •  GGOS / BlueStacks / Free Fire';$status.Text='● SYSTÈME PRÊT'}else{$form.RightToLeft='No';$form.RightToLeftLayout=$false;$sub.Text='Gaming Performance Suite  •  GGOS / BlueStacks / Free Fire';$status.Text='● SYSTEM READY'}})

$timer=New-Object System.Windows.Forms.Timer;$timer.Interval=2000;$timer.Add_Tick({$lp=Get-Process -Name 'HD-Player' -ErrorAction SilentlyContinue;$bs='OFF';if($lp){$bs='ACTIVE'};$live.Text=("CPU LOAD   {0,3}%`r`nRAM USED   {1,4} GB / {2,4} GB`r`nBLUESTACKS {3}`r`n`r`nDISK       HDD={4}  SSD={5}`r`nVIRTUAL    {6}`r`n`r`nPROFILE    FREE FIRE`r`nBS RAM     4 GB`r`nBS CPU     4 CORES`r`nFPS       120 rec / 240 max cap" -f (CpuLoad),(MemUsed),$h.RAM,$bs,$h.HDD,$h.SSD,$h.Virtualization)});$timer.Start()

$form.Add_Shown({$form.Activate()})
[void]$form.ShowDialog()
